version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:14.17.0'
    branches:
      only:
        - dev
    steps:
      - checkout
      - run: 
          command: npm install
      - save_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
          paths:
            - node_modules
      
      