version: 2.1

executors:
  node14:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/project

commands:
  build:
    description: "Builds the project"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package.json" }}
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build for current environment.
          command: npm run build
  test:
    description: "Test Project"
    steps:
      - run:
          name: Test proj
          command: npm run test
  deploy:
    description: "Deploy project to the designated environment"
    parameters:
      env:
        type: string
        default: "test"
    steps:
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --non-interactive --only hosting:<< parameters.env >>

jobs:
  build-deploy-test:
    executor: node14
    steps:
      - build
      - deploy:
          env: "test"
  build-deploy-staging:
    executor: node14
    steps:
      - build
      - deploy:
          env: "staging"
  build-deploy-production:
    executor: node14
    steps:
      - build
      - deploy:
          env: "production"

workflows:
  version: 2
  test:
    jobs:
      - build-deploy-test:
          filters:
            branches:
              only: dev
  staging:
    jobs:
      - build-deploy-staging:
          filters:
            branches:
              only: stag
  production:
    jobs:
      - build-deploy-production:
          filters:
            branches:
              only: main
