version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:14.17.0'
    steps:
      - checkout
      - run:
          name: Firebase Build
          command: npm run build echo "build complete"
  test:
    steps:
      - checkout
      - run:
          name: Firebase Test
          command: npm run test echo "test complete"
  deploy:
    steps:
      - checkout
      - run:
          name: Firebase Deploy
          command: >-
            /node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --only
            hosting:test-react-dev echo "deploy complete"
workflows:
  build:
    jobs:
      - build
      - test
      - deploy: null
        require:
          - build
          - test
        filters:
          branches:
            only:
              - dev
