version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:14.17.0'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: yarn install
      - save_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
          paths:
            - node_modules
      - run: yarn run test
      - run: yarn run build
      - run:
          name: 'Deploy to Firebase Hosting'
          command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'
    