version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:14.17.0'
    steps:
      - checkout
      - run: 
          command: npm install
      - save_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
          paths:
            - node_modules
      - run:
          name: React Build
          command: npm run build
  test:
    docker:
      - image: 'circleci/node:14.17.0'
    steps:
      - checkout
      - run:
          name: React Test
          command: npm install \
                   npm run test
workflows:
  version: 2.1
  react-build:
    jobs:
      - build:
          filters:
            branches:
              only: dev
      - test:
          requires:
            - build
          filters:
            branches:
              only: dev
      
      