version: 2.1
jobs:
  build-test:
    docker:
      - image: 'circleci/node:14.17.0'
    steps:
      - checkout
      - run: 
          command: npm install
      - save_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
          paths:
            - node_modules
      - run:
          name: React Build
          command: npm run build
      - run:
          name: React Test
          command: npm run test
workflows:
  version: 2.1
  build-test-react:
    jobs:
      - build-test:
          filter:
            branches:
              only: dev
      
      