version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:14.17.0'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: yarn install
      - save_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
          paths:
            - node_modules
  workflows:
    build_and_test:
      jobs:
        - run: yarn run test
        - run: yarn run build